---
title: "Perspectives on Suicide Care"
---

<br>
I came across this [Twitter thread by Emily Krebs](https://twitter.com/SaltySicky/status/1568751393086783494) that has articulated insights on suicide care incredibly well: 


> <font size="2.7">Suicidal ideation does not mean a person needs to be immediately hospitalized against their will. A significant portion of the population experiences suicidal ideation and never acts on it. I'd argue that it's a "normal" response to many difficult life situations. Suicidality isn't always episodic. That means that for some people, the desire to die never goes away. We wake up, think about it, and carry on with our day. I've seen this called "grey suicidality" online and it's fairly common. Again, not an emergency.</font> 

> <font size="2.5">Reporting someone for being suicidal can get them kicked out of college & fired from jobs. It can even cause them to lose custody of their kids. **Mandatory reporting policies are dangerous & are aimed at protecting businesses and organizations from liability, not helping people.** There are many ways to handle mental health crises that don't involve cops or involuntary psychiatric care. Access to childcare, meals, emergency funds, and affordable medical care can go a long way. Being in a community where people can talk openly about suicidality is huge. The United Nations has called involuntary psychiatric care a form of torture but it's still regularly practiced on suicidal patients in the US. Involuntary 72-hour ("5150") holds are the norm for people deemed a threat to themselves. During this time, consent goes out the window. 5150 holds are one of the only legal circumstances in the USA where people can be forced to undergo medical treatments and ingest food or liquids against their will. (The other circumstances include treatment of minors, intellectually disabled adults, and incarcerated people.) Suicide risk following involuntary psychiatric hospitalization skyrockets [$^1$](https://pubmed.ncbi.nlm.nih.gov/31162700/) [$^2$](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5710249/). While 5150 holds may prevent a person from dying in one moment of crisis, they don't protect people long term. #988Lifeline openly engages in nonconsensual active rescue despite its harms and lack of effectiveness. **Callers seeking phone support can end up being escorted by police to a psychiatric hospital against their will--sometimes at gunpoint if the officers deem the person dangerous.**</font> 

> <font size="2.5">There are crisis hotlines that don't engage with police or nonconsensual active rescue. 988 is NOT one of these safe hotlines. Instead, check out [Trans Lifeline](https://translifeline.org/), [Call BlackLine](https://www.callblackline.com/), & [Samaritans NYC](https://samaritansnyc.org/). If you want to learn about anti-carceral mental healthcare practices (meaning care where patients don't lose their rights or autonomy), check out [Project LETS](https://linktr.ee/projectlets), [Fireweed Collective](https://fireweedcollective.org/), [Institute for the Development of Human Arts](https://www.idha-nyc.org/), [Mad In America](https://www.madinamerica.com/), and [Trans Lifeline](https://translifeline.org/). If you're looking to understand the perspectives of suicide survivors, [Live Through This](https://livethroughthis.org/) has an incredible collection of narratives shared by these people. It's publicly available online. Definite content warnings though! They often discuss methods and other triggering concepts in depth.</font>  
