---
title: "Resources On Data Analysis"
output:
  html_document
---

<style type="text/css">
  .title{
    color: #294759;
    margin-bottom: -1%;
    font-size: 18pt
  }
  body {
    font-size: 12pt;
    color: #294759;
    line-height: 0.8cm;
  }
  h4 {
    font-size: 16pt;
    color: #294759;
    margin-bottom: 20px;
  }
</style>

```{r include=FALSE}
colorize <- function(x, color) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color,
      x)
  } else x
}
```

<br>

#### **Free Resources On Learning R**
* There are many free resources out there about learning R and related languages, and the incredible database [**resouRces**](https://www.resourcesdatabase.com/resources/learning_r.html) literally has it all!

* [Psych #rstats Club](https://docs.google.com/spreadsheets/d/1cbOyYoR4CCb4zYvKy2dGgeuKfeRhyA5qS24EdYFHDQY/edit#gid=0) is a list of resources for using R in psychology.

***

#### **Multilevel Modeling (MLM)**
* [An Introduction to Hierarchical Modeling](http://mfviz.com/hierarchical-models/): a very nice animated visualization for understanding mixed-effects models
* [Understanding and analyzing multilevel data from real-time monitoring studies: An easily- accessible tutorial using R](https://psyarxiv.com/xf2pw/) by [Dr. Evan Kleiman](https://kleimanlab.org/)
* A comprehensive tutorial with sample code and data by Penn State: [Intensive Longitudinal Data: Analysis of Experience Sampling and EMA Data](https://quantdev.ssri.psu.edu/resources/intensive-longitudinal-data-analysis-experience-sampling-and-ema-data)

***

#### **Building a Website**

I built this website hosted on GitHub using R markdown. It comes with templates and is completely free. You don't need advanced programming knowledge to get started. [Learn to build your own here.](https://github.com/skills/github-pages)


***

#### **Data Visualization**

* [How to pick more beautiful colors for your data visualizations](https://www.resourcesdatabase.com/resources/visualization.html)
* Colors are a great way to capture attention. However, 5-8% men and 0.5-1% women experience color blindness. This [website](https://davidmathlogic.com/colorblind/#%23D81B60-%231E88E5-%23FFC107-%23004D40) simulates what people with different kinds of color blindness see and shows how some existing colorblind-friendly palettes actually don’t do a good job. 
* These are my personal favorite colorblind-friendly colors:   
  + `r colorize("#0C7BDC", "#0C7BDC")`
  + `r colorize("#FFC20A", "#FFC20A")`
  + `r colorize("#7D2F39", "#7D2F39")`
  + `r colorize("#FF6999", "#FF6999")`
  
---
<p style = "font-size: 11.5pt; font-weight: 500">Share your comments, concerns, suggestions, or additional resources [here](https://forms.gle/DQfojqWRTGQ8mjq2A).   
Page last updated: `r Sys.Date()`</p>
