---
title: "Recent Work"
---

<br/>
**Preprints**   

*Xu, I.*, Passell, E., Strong, R., Grinspoon, L., Wu, C., Jung, L., Wilmer, J., & Germine, L. (2022). No evidence for consistent reliability across 36 variations of the emotional dot probe task in 9,000 participants. [Preprint](www.psyarxiv.com/58z4n)

<br/>
**Posters**    

**Xu, I.**, Hawks, Z., Wu, C., Ferreira, M., Bowers, E., Strong, R., Li, F., Grinspoon, E., Beard, C., Germine, L. (Sept 2022). Patient Responses to Return of Research Results in two EMA Studies of Cognition and Emotion. Presented at Society for Research in Psychopathology, Philadelphia, PA. [Link](docs.google.com/presentation/d/1-WbuhEclD7IrZZjmDVyVom3fcIL_4GPd/edit?usp=sharing&ouid=100799767484704214514&rtpof=true&sd=true)

Grinspoon, E., Jung, L., Li, F., Passell, E., Scheuer, L., Hawks, Z., Strong, R., Singh, S., **Xu, I.**, & Germine, L. (Sept 2022). How Does Returning Cognitive Test Results Impact Performance over Time? Presented at Society for Research in Psychopathology, Philadelphia, PA. [Link](docs.google.com/presentation/d/1II4foE8VE4SZqOMAfn9_np9FM38qJ6FV0fulmYlXPAw/edit?usp=sharing)

Wu, C., **Xu, I.**, Passell, E., Beard, C., & Germine, L. (March 2022). The Older, the Merrier: Older Adults Have Greater Positive Interpretation Biases. Presented at Harvard Psychiatry Research Day. Cambridge, MA. [Link](docs.google.com/presentation/d/1UTG1GWxcFLKsCgSQqMXULOJ_6i_-IvXWxxqIvZqVy2E/edit?usp=sharing)


**Xu, I.**, Passell, E., Strong, R., Grinspoon, E., & Germine, L. (March 2022). Attentional Bias for Threat: Reliability of 36 Versions of the Threat Dot Probe Task. Presented at Harvard Psychiatry Research Day, Cambridge, MA. [Link](docs.google.com/presentation/d/1aCFDA1ghLOf54COhUPxD1bBCbIa4845D/edit?usp=sharing&ouid=100799767484704214514&rtpof=true&sd=true)