---
title: "Finding Suicide Labs"
output: html_document
---

<style>
  .title{
    color: #294759;
    margin-bottom: -1%;
    font-size: 18pt
  }
  body {
    font-size: 12pt;
    color: #294759;
    line-height: 1.8em;
  }
  h4 {
    font-size: 15pt;
    margin-bottom: 20px;
  }
</style>

<br>


To reduce barriers for students passionate about suicide research, especially those from underrepresented backgrounds, there has been efforts to put together resources on finding researchers, research labs, and organizations in the suicide and self-injury field. 

* [Psychin'Out](https://www.psychinout.org/) has a list of [PhD Advisor Directory](https://docs.google.com/spreadsheets/d/1SB-y2AxbDhu5UGZbdh-GQ9DemBVPFfz0sW-pb6LW5j8/edit#gid=663188846) organized by research interests including suicide and self-injury.

* [Dr. Blaire Ehret](https://twitter.com/BlaireEhretPhD) has a [list](https://docs.google.com/spreadsheets/d/1pFkelS0l678qHVlEmLMwFcDo8k_5dP3MNYY5Ju_e_7Y/edit#gid=1078021192) on suicide faculty accepting students in  particular years. 

* [Dr. Abby Ridge-Anderson](https://twitter.com/AbbyAraCUA) has a website on [Resources For Suicide Researchers](https://abbyraphd.github.io/SRSToolbox/resources.html) that involve suicide related networking, organizations, conferences, training, measures, datasets, etc. 

* To learn about current research or present your work at early-career-friendly conferences, there are two free virtual conferences that I've had good experience with: [Suicide Research Symposium (SRS)](https://www.suicideresearchsymposium.com/home) and [Youth Suicide Research Consortium (YSRC)](https://www.youthsuicideresearch.org/). 

***

Since the existing lists are organized by particular application cycles, I tried to compile a list of <u>**faculty and researchers specializing in the field of suicide and self injury and are able to admit students or RAs**</u>.   

This list has columns indicating

1. if the researcher *can* accept grad students or RAs, and   
2. if they plan to accept grad student(s) in the *current cycle*.   

The list includes not just researchers in the field of clinical psychology, but also the field of psychiatry, neuroscience, social work, public health, etc. While clinical psychology is where most of the research resides in, I believe that suicide prevention benefits from interdisciplinary collaborations and want to show early career scholars that there are many potential career paths where you can contribute to suicide research.      

[Open and edit the list in Google Sheet](https://docs.google.com/spreadsheets/d/1SV8bvFvMJQcHBq3tapgODfbhxloYd-Tmwaegvvj-xU8/edit?usp=sharing) or preview below. Please help maintain this list as we rely on <span style = "color: #FF6999"><u>community efforts</u></span>! 

<iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQJsK_uW93kUpG4T2R1X4Rhc2XL9y0U99hMX07AwZbw0cNUWettev0ieHU6N6rTHWaUdcDNxXOcO-14/pubhtml?widget=true&amp;headers=false"  width="110%" height="800"></iframe>

---
<p style = "font-size: 11.5pt; font-weight: 500">Share your comments, concerns, suggestions, or additional resources [here](https://forms.gle/DQfojqWRTGQ8mjq2A).   
Page last updated: `r Sys.Date()`</p>
